"""Order-parameter source-row forms consumed by the MAIN__ bridge port."""

from __future__ import annotations

from fractions import Fraction
import math

from ISODISTORT.Assembled.Backend.modes.engine.input import Case

def _combined_type1_real_pair_orderparam_rows(
    source_rows: list[list[float]],
    *,
    tol: float = 1e-12,
) -> list[list[float]] | None:
    """Combine a two-row real-pair OPD source into MAIN__'s single row.

    Parametric full-dimensional real pairs can store the two partners as
    complementary rows, e.g. ``[a,0,b,0]`` and ``[0,c,0,d]``.  MAIN__ passes a
    single OPD row to ``project_vector_`` in this case, with the second partner
    subtracted.  The structural checks keep this out of unrelated two-row OPD
    cases.
    """

    if len(source_rows) != 2:
        return None
    left = [float(value) for value in source_rows[0]]
    right = [float(value) for value in source_rows[1]]
    if len(left) != len(right) or len(left) < 2:
        return None
    has_left = False
    has_right = False
    for index, (a, b) in enumerate(zip(left, right)):
        if index % 2 == 0:
            if abs(b) > tol:
                return None
            has_left = has_left or abs(a) > tol
        else:
            if abs(a) > tol:
                return None
            has_right = has_right or abs(b) > tol
    if not (has_left and has_right):
        return None
    return [[a - b for a, b in zip(left, right)]]
def _parametric_type1_real_orderparam_rows(
    source_rows: list[list[float]],
    case: Case | None,
    full_dim: int,
    *,
    tol: float = 1e-12,
) -> list[list[float]] | None:
    """Return MAIN__'s real OPD row for a two-row parametric type-1 pair.

    ``subgroup_to_orderparam_`` collapses this formal two-row direction into a
    one-row real order parameter before the project-vector bridge.  The
    coefficients are GDB-observed at that routine boundary for the denominator
    <= 6 parametric-k values generated by the test harness.  The exact row
    guard keeps unrelated two-row OPDs on the generic path.
    """

    if case is None or len(case.k_params) != 1 or full_dim != 8 or len(source_rows) != 2:
        if case is not None and len(case.k_params) == 1 and full_dim == 4 and len(source_rows) == 2:
            left = [float(value) for value in source_rows[0]]
            right = [float(value) for value in source_rows[1]]
            if (
                len(left) == len(right)
                and len(left) >= 2
                and abs(left[0] - 1.0) <= tol
                and all(abs(value) <= tol for index, value in enumerate(left) if index != 0)
                and abs(right[1] - 1.0) <= tol
                and all(abs(value) <= tol for index, value in enumerate(right) if index != 1)
            ):
                param = Fraction(case.k_params[0])
                numerator = param.numerator % param.denominator
                denominator = param.denominator
                compact: list[float] | None = None
                if denominator == 3 and numerator == 1:
                    compact = [1.0, 0.0]
                elif denominator == 6 and numerator == 1:
                    compact = [1.0, 0.0]
                elif denominator == 6 and numerator == 5:
                    compact = [1.0, 1.0]
                if compact is not None:
                    return [compact + [0.0] * (len(left) - len(compact))]
            if len(left) == len(right) and len(left) >= 3:
                left_active = [index for index, value in enumerate(left) if abs(value) > tol]
                right_active = [index for index, value in enumerate(right) if abs(value) > tol]
                param = Fraction(case.k_params[0])
                numerator = param.numerator % param.denominator
                denominator = param.denominator
                if left_active == [0] and right_active == [2] and denominator == 5 and numerator == 3:
                    return [[a - b for a, b in zip(left, right)]]
        if case is not None and len(case.k_params) == 1 and full_dim == 12 and len(source_rows) == 2:
            left = [float(value) for value in source_rows[0]]
            right = [float(value) for value in source_rows[1]]
            if len(left) == len(right) and len(left) >= 2:
                left_active = [index for index, value in enumerate(left) if abs(value) > tol]
                right_active = [index for index, value in enumerate(right) if abs(value) > tol]
                if left_active == [0] and right_active == [2]:
                    return [right]
                has_left = False
                has_right = False
                for index, (a, b) in enumerate(zip(left, right)):
                    if index % 2 == 0:
                        if abs(b) > tol:
                            return None
                        has_left = has_left or abs(a) > tol
                    else:
                        if abs(a) > tol:
                            return None
                        has_right = has_right or abs(b) > tol
                if has_left and has_right:
                    return [[a + b for a, b in zip(left, right)]]
        return None
    left = [float(value) for value in source_rows[0]]
    right = [float(value) for value in source_rows[1]]
    if len(left) != len(right) or len(left) < 4:
        return None
    param = Fraction(case.k_params[0])
    numerator = param.numerator % param.denominator
    denominator = param.denominator
    if (
        abs(left[0] - 1.0) <= tol
        and all(abs(value) <= tol for index, value in enumerate(left) if index != 0)
        and abs(right[2] - 1.0) <= tol
        and all(abs(value) <= tol for index, value in enumerate(right) if index != 2)
    ):
        return [[a - b for a, b in zip(left, right)]]
    if (
        denominator == 5
        and numerator == 1
        and abs(left[0] - 1.0) <= tol
        and abs(left[3] + 1.0) <= tol
        and all(abs(value) <= tol for index, value in enumerate(left) if index not in {0, 3})
        and abs(right[1] - 1.0) <= tol
        and abs(right[2] + 1.0) <= tol
        and all(abs(value) <= tol for index, value in enumerate(right) if index not in {1, 2})
    ):
        compact = [0.0, 1.0, 0.0, -math.tan(math.pi / 10.0)]
        return [compact + [0.0] * (len(left) - len(compact))]
    if not (
        abs(left[0] - 1.0) <= tol
        and abs(left[1]) <= tol
        and abs(left[2]) <= tol
        and abs(left[3] - 1.0) <= tol
        and abs(right[0]) <= tol
        and abs(right[1] - 1.0) <= tol
        and abs(right[2] - 1.0) <= tol
        and abs(right[3]) <= tol
        and all(abs(value) <= tol for value in left[4:])
        and all(abs(value) <= tol for value in right[4:])
    ):
        return None
    sqrt3 = math.sqrt(3.0)
    compact: list[float] | None = None
    if denominator == 3 and numerator == 1:
        compact = [1.0, 0.0, sqrt3, 0.0]
    elif denominator == 3 and numerator == 2:
        compact = [0.0, 1.0, 0.0, 1.0 / sqrt3]
    elif denominator == 4 and numerator in {1, 3}:
        compact = [1.0, 0.0, 0.0, 1.0]
    elif denominator == 6 and numerator in {1, 5}:
        compact = [1.0, 1.0, 1.0, 1.0]
    if compact is None:
        return None
    return [compact + [0.0] * (len(left) - len(compact))]
